### ISSUE TITLE
NPE on shutdown

### ISSUE THREAD

**Issue by dernasherbrezon** [dernasherbrezon/r2cloud#70]
```
Dec 01 06:52:03 raspberrypi java[10669]: unable to process: /home/pi/r2cloud/./data/satellites/40069/data/1575179923348/output.raw.gz
Dec 01 06:52:03 raspberrypi java[10669]: java.lang.NullPointerException
Dec 01 06:52:03 raspberrypi java[10669]:         at ru.r2cloud.jradio.lrpt.LRPT.decode(LRPT.java:63)
Dec 01 06:52:03 raspberrypi java[10669]:         at ru.r2cloud.jradio.lrpt.LRPT.readBytes(LRPT.java:52)
Dec 01 06:52:03 raspberrypi java[10669]:         at ru.r2cloud.jradio.BeaconSource.hasNext(BeaconSource.java:34)
Dec 01 06:52:03 raspberrypi java[10669]:         at ru.r2cloud.satellite.decoder.LRPTDecoder.decode(LRPTDecoder.java:53)
Dec 01 06:52:03 raspberrypi java[10669]:         at ru.r2cloud.satellite.decoder.DecoderTask.run(DecoderTask.java:36)
Dec 01 06:52:03 raspberrypi java[10669]:         at ru.r2cloud.satellite.Scheduler$1$1.run(Scheduler.java:160)
Dec 01 06:52:03 raspberrypi java[10669]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Dec 01 06:52:03 raspberrypi java[10669]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Dec 01 06:52:03 raspberrypi java[10669]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Dec 01 06:52:03 raspberrypi java[10669]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Dec 01 06:52:03 raspberrypi java[10669]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Dec 01 06:52:03 raspberrypi java[10669]:         at java.base/java.lang.Thread.run(Thread.java:834)
Dec 01 06:52:03 raspberrypi java[10669]:  [ru.r2cloud.satellite.decoder.LRPTDecoder decode]
```

**Comment by dernasherbrezon** [comment]
Fixed in jradio: https://github.com/dernasherbrezon/jradio/commit/9f06530cc2efaa3ae628bcbdf748627c537e9865
